//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.01 at 05:01:38 PM CEST 
//

package nl.mok.mastersofcode.shared.domain.meta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * Represents the assignment data as stored in an assignment.xml file. This
 * class is generated using JAXB. This class is only used for extracting xml
 * data.
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * *REMOVED THIS JIBBERISH*
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "metadata", "files", "tests", "hints" })
@XmlRootElement(name = "assignment")
public class Assignment {

	@XmlElement(required = true)
	protected Assignment.Metadata metadata;
	@XmlElement(required = true)
	protected Assignment.Files files;
	@XmlElement(required = true)
	protected Assignment.Tests tests;
	@XmlElement(required = true)
	protected Assignment.Hints hints;

	/**
	 * Gets the value of the metadata property.
	 * 
	 * @return possible object is {@link Assignment.Metadata }
	 * 
	 */
	public Assignment.Metadata getMetadata() {
		return metadata;
	}

	/**
	 * Sets the value of the metadata property.
	 * 
	 * @param value
	 *            allowed object is {@link Assignment.Metadata }
	 * 
	 */
	public void setMetadata(Assignment.Metadata value) {
		this.metadata = value;
	}

	/**
	 * Gets the value of the files property.
	 * 
	 * @return possible object is {@link Assignment.Files }
	 * 
	 */
	public Assignment.Files getFiles() {
		return files;
	}

	/**
	 * Sets the value of the files property.
	 * 
	 * @param value
	 *            allowed object is {@link Assignment.Files }
	 * 
	 */
	public void setFiles(Assignment.Files value) {
		this.files = value;
	}

	/**
	 * Gets the value of the tests property.
	 * 
	 * @return possible object is {@link Assignment.Tests }
	 * 
	 */
	public Assignment.Tests getTests() {
		return tests;
	}

	/**
	 * Sets the value of the tests property.
	 * 
	 * @param value
	 *            allowed object is {@link Assignment.Tests }
	 * 
	 */
	public void setTests(Assignment.Tests value) {
		this.tests = value;
	}

	/**
	 * Gets the value of the hints property.
	 * 
	 * @return possible object is {@link Assignment.Hints }
	 * 
	 */
	public Assignment.Hints getHints() {
		return hints;
	}

	/**
	 * Sets the value of the hints property.
	 * 
	 * @param value
	 *            allowed object is {@link Assignment.Hints }
	 * 
	 */
	public void setHints(Assignment.Hints value) {
		this.hints = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * *REMOVED THIS JIBBERISH*
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "file" })
	public static class Files {

		@XmlElement(required = true)
		protected List<Assignment.Files.File> file;

		/**
		 * Gets the value of the file property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the file property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getFile().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Assignment.Files.File }
		 * 
		 * 
		 */
		public List<Assignment.Files.File> getFile() {
			if (file == null) {
				file = new ArrayList<Assignment.Files.File>();
			}
			return this.file;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * *REMOVED THIS JIBBERISH*
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class File {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "path", required = true)
			protected String path;
			@XmlAttribute(name = "write", required = true)
			protected boolean write;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the path property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPath() {
				return path;
			}

			/**
			 * Sets the value of the path property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPath(String value) {
				this.path = value;
			}

			/**
			 * Gets the value of the write property.
			 * 
			 */
			public boolean isWrite() {
				return write;
			}

			/**
			 * Sets the value of the write property.
			 * 
			 */
			public void setWrite(boolean value) {
				this.write = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * *REMOVED THIS JIBBERISH*
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "hint" })
	public static class Hints {

		protected List<Assignment.Hints.Hint> hint;

		/**
		 * Gets the value of the hint property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the hint property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getHint().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Assignment.Hints.Hint }
		 * 
		 * 
		 */
		public List<Assignment.Hints.Hint> getHint() {
			if (hint == null) {
				hint = new ArrayList<Assignment.Hints.Hint>();
			}
			return this.hint;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * *REMOVED THIS JIBBERISH*
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class Hint {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "text", required = true)
			protected String text;
			@XmlAttribute(name = "time", required = true)
			protected short time;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the text property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getText() {
				return text;
			}

			/**
			 * Sets the value of the text property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setText(String value) {
				this.text = value;
			}

			/**
			 * Gets the value of the time property.
			 * 
			 */
			public short getTime() {
				return time;
			}

			/**
			 * Sets the value of the time property.
			 * 
			 */
			public void setTime(short value) {
				this.time = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * *REMOVED THIS JIBBERISH*
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "name", "participants", "spectators",
			"creator" })
	public static class Metadata {

		@XmlElement(required = true)
		protected String name;
		@XmlElement(required = true)
		protected String participants;
		@XmlElement(required = true)
		protected String spectators;
		@XmlElement(required = true)
		protected Assignment.Metadata.Creator creator;

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * Gets the value of the participants property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getParticipants() {
			return participants;
		}

		/**
		 * Sets the value of the participants property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setParticipants(String value) {
			this.participants = value;
		}

		/**
		 * Gets the value of the spectators property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSpectators() {
			return spectators;
		}

		/**
		 * Sets the value of the spectators property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSpectators(String value) {
			this.spectators = value;
		}

		/**
		 * Gets the value of the creator property.
		 * 
		 * @return possible object is {@link Assignment.Metadata.Creator }
		 * 
		 */
		public Assignment.Metadata.Creator getCreator() {
			return creator;
		}

		/**
		 * Sets the value of the creator property.
		 * 
		 * @param value
		 *            allowed object is {@link Assignment.Metadata.Creator }
		 * 
		 */
		public void setCreator(Assignment.Metadata.Creator value) {
			this.creator = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * *REMOVED THIS JIBBERISH*
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "organisation", "link" })
		public static class Creator {

			@XmlElement(required = true)
			protected String name;
			@XmlElement(required = true)
			protected String organisation;
			@XmlElement(required = true)
			@XmlSchemaType(name = "anyURI")
			protected String link;

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setName(String value) {
				this.name = value;
			}

			/**
			 * Gets the value of the organisation property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getOrganisation() {
				return organisation;
			}

			/**
			 * Sets the value of the organisation property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setOrganisation(String value) {
				this.organisation = value;
			}

			/**
			 * Gets the value of the link property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getLink() {
				return link;
			}

			/**
			 * Sets the value of the link property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setLink(String value) {
				this.link = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * *REMOVED THIS JIBBERISH*
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "test" })
	public static class Tests {

		@XmlElement(required = true)
		protected List<Assignment.Tests.Test> test;

		/**
		 * Gets the value of the test property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the test property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getTest().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Assignment.Tests.Test }
		 * 
		 * 
		 */
		public List<Assignment.Tests.Test> getTest() {
			if (test == null) {
				test = new ArrayList<Assignment.Tests.Test>();
			}
			return this.test;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * *REMOVED THIS JIBBERISH*
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class Test {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "name", required = true)
			protected String name;
			@XmlAttribute(name = "description", required = true)
			protected String description;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the name property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getName() {
				return name;
			}

			/**
			 * Sets the value of the name property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setName(String value) {
				this.name = value;
			}

			/**
			 * Gets the value of the description property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDescription(String value) {
				this.description = value;
			}

		}

	}

}
