// Including ngTranslate
angular.module("ngTranslate",["ng"]).config(["$provide",function(t){$TranslateProvider=function(){var t,n={};this.translations=function(t,r){if(!t&&!r)return n;if(t&&!r){if(angular.isString(t))return n[t];n=t}else n[t]=r},this.uses=function(r){if(!r)return t;if(!n[r])throw Error("$translateProvider couldn't find translationTable for langKey: '"+r+"'");t=r},this.$get=["$interpolate","$log",function(r,a){return $translate=function(e,i){var l=t?n[t][e]:n[e];return l?r(l)(i):(a.warn("Translation for "+e+" doesn't exist"),e)},$translate.uses=function(n){return n?(t=n,void 0):t},$translate}]},t.provider("$translate",$TranslateProvider)}]),angular.module("ngTranslate").directive("translate",["$filter","$interpolate",function(t,n){var r=t("translate");return{restrict:"A",scope:!0,link:function(t,a,e){e.$observe("translate",function(r){t.translationId=angular.equals(r,"")?n(a.text())(t.$parent):r}),e.$observe("values",function(n){t.interpolateParams=n}),t.$watch("translationId + interpolateParams",function(){a.html(r(t.translationId,t.interpolateParams))})}}}]),angular.module("ngTranslate").filter("translate",["$parse","$translate",function(t,n){return function(r,a){return angular.isObject(a)||(a=t(a)()),n(r,a)}}]);

// Configuring your module, asking for ngTranslate as dependency
angular.module('translator', ['ngTranslate']).config(['$translateProvider', function ($translateProvider) {
	// Configuring $translateProvider
    // Simply register translation table as object hash
    $translateProvider.translations('en_EN', {
    	'TITLE' : 'Masters of Code',
    	'DASHBOARD' : 'Dashboard',
    	'COMPETITION_NOT_STARTED' : 'The competition has not yet started.',
    	'ACTIVE' : 'Active',
    	'NOT_ACTIVE' : 'Not Active',
    	'DIFFICULTY' : 'Difficulty',
    	'HARD' : 'Hard',
    	'EASY' : 'Easy',
    	'DURATION' : 'Duration',
    	'VIEW_SCORES' : 'View scores',
    	'SCORE' : 'Score',
    	'SCORES' : 'Scores',
    	'ROUNDS' : 'Rounds',
    	'ROUND' : 'Round',
    	'VIEW_ROUNDS' : 'View rounds',
    	'EDITOR' : 'Editor',
    	'SHORTCUTS' : 'Shortcuts',
    	'FORMAT_CODE' : 'Format code',
    	'ASSIGNMENT' : 'Assignment',
    	'FILES' : 'Files',
    	'TESTS' : 'Tests',
    	'HINTS' : 'Hints',
    	'NEWS_FEED' : 'News feed',
    	'ASSIGNMENT_DESCRIPTION' : 'Assignment description',
    	'CREATOR_NAME' : 'Creator name',
    	'CREATOR_ORGANISATION' : 'Creator organisation',
    	'CREATOR_LINK' : 'Creator link',
    	'ROUND_DURATION' : 'Round duration',
    	'SAVE' : 'Save',
    	'COMPILE' : 'Compile',
    	'TEST_ALL' : 'Test all',
    	'SUBMIT' : 'Submit',
    	'CLEAR_CONSOLE' : 'Clear console',
        'LOG_OUT' : 'Log out',
        'EDIT_TEAM' : 'Edit team',
        'LANGUAGE' : 'Language',
        'LANGUAGE_ENGLISH' : 'English',
        'LANGUAGE_DUTCH' : 'Dutch',
		'PARTICIPANT_DESCRIPTION' : 'Participant description',
		'SPECTATOR_DESCRIPTION' : 'Spectator description',
		'CANCEL' : 'Cancel',
		'ASSIGNMENTS' : 'Assignments',
		'ARTIFACT' : 'Artifact',
		'ADD_ASSIGNMENT' : 'Add Assignment',
		'CREATE_COMPETITION' : 'Create competition',
		'TITLE_TITLE' : 'Title',
		'DESCRIPTION' : 'Description',
		'STATUS' : 'Status',
		'COMPETITION_OVERVIEW' : 'Competition overview',
		'SAVE_COMPETITION' : 'Save competition',
		'DELETE_COMPETITION' : 'Delete competition',
		'START_COMPETITION' : 'Start competition',
		'STOP_COMPETITION' : 'Stop competition',
		'NODE_OVERVIEW' : 'Node Overview',
		'TEAMS' : 'Teams',
		'PARTICIPANTS' : 'Participants',
		'TIME' : 'Time',
		'TEXT' : 'Text',
		'TIME_SECONDS' : 'Time (Seconds)',
		'THE_MESSAGE_THAT_WILL_BE_DISPLAYED' : 'The message that will be displayed.',
		'ADD_HINT' : 'Add Hint',
		'ADD_NODE' : 'Add node',
		'JDNI_NAME' : 'JDNI Name',
		'NODE' : 'Node',
		'EDIT_NODE' : 'Edit Node',
		'DELETE_NODE' : 'Delete Node',
		'ADD_PARTICIPANT' : 'Add Participant',
		'MULTIPLIER' : 'Multiplier',
		'DURATION_SECONDS' : 'Duration (Seconds)',
		'ADD_ROUND' : 'Add Round',
		'EDIT_ROUND' : 'Edit Round',
		'START_ROUND' : 'Start Round',
		'PAUSE_ROUND' : 'Pause Round',
		'RESUME_ROUND' : 'Resume Round',
		'DELETE_ROUND' : 'Delete Round',
		'FREEZE_ROUND' : 'Freeze Round',
		'STOP_ROUND' : 'Stop Round',
		'TEAM' : 'Team',
		'MEMBERS' : 'Members',
		'MEMBER' : 'Member',
		'LEADER' : 'Leader',
		'ADD_TEAM' : 'Add Team',
		'REMOVE_TEAM' : 'Remove Team',
		'TITLE_ADD_ASSIGNMENT' : 'Masters of Code - Add Assignment',
		'CREATOR' : 'Creator',
		'NAME' : 'Name',
		'ROUND_INFO' : 'Round information',
		'NAME_NODE' : 'The name of the node',
		'TITLE_ADD_ROUND' : 'Masters of Code - Add Round',
		'DELETE_TEAM' : 'Delete team',
		'ADD_TO_COMPETITION' : 'Add to competition',
		'REMOVE_FROM_COMPETITION' : 'Remove from competition'
    });   

    $translateProvider.translations('nl_NL', {
    	'TITLE' : 'Masters of Code',
    	'DASHBOARD' : 'Overzicht',
    	'COMPETITION_NOT_STARTED' : 'De competitie is nog niet gestart.',
    	'ACTIVE' : 'Actief',
    	'NOT_ACTIVE' : 'Niet actief',
    	'DIFFICULTY' : 'Moeilijkheid',
    	'HARD' : 'Moeilijk',
    	'EASY' : 'Makkelijk',
    	'DURATION' : 'Tijdsduur',
    	'VIEW_SCORES' : 'Scores',
    	'SCORES' : 'Scores',
    	'SCORE' : 'Score',
    	'ROUNDS' : 'Rondes',
    	'ROUND' : 'Ronde',
    	'VIEW_ROUNDS' : 'Toon rondes',
    	'EDITOR' : 'Editor',
    	'SHORTCUTS' : 'Snelkoppelingen',
    	'FORMAT_CODE' : 'Formatteer code',
    	'ASSIGNMENT' : 'Opdracht',
    	'FILES' : 'Bestanden',
    	'TESTS' : 'Testen',
    	'HINTS' : 'Hints',
    	'NEWS_FEED' : 'Nieuws overzicht',
    	'ASSIGNMENT_DESCRIPTION' : 'Opdracht omschrijving',
    	'CREATOR_NAME' : 'Auteur naam',
    	'CREATOR_ORGANISATION' : 'Auteur organisatie',
    	'CREATOR_LINK' : 'Auteur website',
    	'ROUND_DURATION' : 'Tijdsduur ronde',
    	'SAVE' : 'Opslaan',
    	'COMPILE' : 'Compileren',
    	'TEST_ALL' : 'Test alles',
    	'SUBMIT' : 'Inleveren',
    	'CLEAR_CONSOLE' : 'Wis console',
    	'LOG_OUT' : 'Log uit',
    	'EDIT_TEAM' : 'Wijzig team',
        'LANGUAGE' : 'Taal',
        'LANGUAGE_ENGLISH' : 'Engels',
        'LANGUAGE_DUTCH' : 'Nederlands',
		'PARTICIPANT_DESCRIPTION' : 'Omschrijving deelnemer',
		'SPECTATOR_DESCRIPTION' : 'Omschrijving toeschouwer',
		'CANCEL' : 'Annuleren',
		'ASSIGNMENTS' : 'Opdrachten',
		'ARTIFACT' : 'Artifact',
		'ADD_ASSIGNMENT' : 'Upload opdracht',
		'CREATE_COMPETITION' : 'Maak competitie',
		'TITLE_TITLE' : 'Titel',
		'DESCRIPTION' : 'Omschrijving',
		'STATUS' : 'Status',
		'COMPETITION_OVERVIEW' : 'Competitie overzicht',
		'SAVE_COMPETITION' : 'Sla competitie op',
		'DELETE_COMPETITION' : 'Verwijder competitie',
		'START_COMPETITION' : 'Start competitie',
		'STOP_COMPETITION' : 'Stop competitie',
		'NODE_OVERVIEW' : 'Node overzicht',
		'TEAMS' : 'Teams',
		'PARTICIPANTS' : 'Deelnemers',
		'TIME' : 'Tijd',
		'TEXT' : 'Tekst',
		'TIME_SECONDS' : 'Tijd (Seconden)',
		'THE_MESSAGE_THAT_WILL_BE_DISPLAYED' : 'Het bericht dat getoond wordt.',
		'ADD_HINT' : 'Voeg hint toe',
		'ADD_NODE' : 'Voeg node toe',
		'JDNI_NAME' : 'JDNI naam',
		'NODE' : 'Node',
		'EDIT_NODE' : 'Pas node aan',
		'DELETE_NODE' : 'Verwijder node',
		'ADD_PARTICIPANT' : 'Voeg deelnemer toe',
		'MULTIPLIER' : 'Moeilijkheid',
		'DURATION_SECONDS' : 'Tijdsduur (Seconden)',
		'ADD_ROUND' : 'Voeg ronde toe',
		'EDIT_ROUND' : 'Pas ronde aan',
		'START_ROUND' : 'Start ronde',
		'PAUSE_ROUND' : 'Pauzeer ronde',
		'RESUME_ROUND' : 'Hervat ronde',
		'DELETE_ROUND' : 'Verwijder ronde',
		'FREEZE_ROUND' : 'Bevries ronde',
		'STOP_ROUND' : 'Stop ronde',
		'TEAM' : 'Team',
		'MEMBERS' : 'Teamleden',
		'MEMBER' : 'Teamlid',
		'LEADER' : 'Teamleider',
		'ADD_TEAM' : 'Voeg team toe',
		'REMOVE_TEAM' : 'Verwijder team',
		'TITLE_ADD_ASSIGNMENT' : 'Masters of Code - Voeg opdracht toe',
		'CREATOR' : 'Auteur',
		'NAME' : 'Naam',
		'ROUND_INFO' : 'Ronde information',
		'NAME_NODE' : 'De naam van de node',
		'TITLE_ADD_ROUND' : 'Masters of Code - Voeg ronde toe',
		'DELETE_TEAM' : 'Verwijder team',
		'ADD_TO_COMPETITION' : 'Voeg toe aan competitie',
		'REMOVE_FROM_COMPETITION' : 'Verwijder uit competitie'
    		
    });   
    
    if (!angular.isUndefined(window.sessionStorage.language)) {
     
       	if (window.sessionStorage.language == "en_EN") {     
       		$translateProvider.uses('en_EN')     	
    	} else if (window.sessionStorage.language == "nl_NL") {    	
    		$translateProvider.uses('nl_NL')     	
    	} 
     } else {
 		$translateProvider.uses('en_EN')
 	}
}]).controller('TranslateController', ['$translate', '$scope', function ($translate, $scope) {
   
}]);

